[tool.poetry]
name = "biotrainer"
version = "0.2.0"
description = "Biotrainers for embeddings"
authors = [
    "Christian Dallago <christian.dallago@tum.de>",
    "Sebastian Franz <sebastian.franz@tum.de>",
    "Michael Heinzinger <mheinzinger@rostlab.org>"
]
license = "AFL v3.0"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: AFL License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Visualization"
]

[tool.poetry.scripts]
biotrainer = 'biotrainer.utilities.cli:main'

[tool.poetry.urls]
issues = "https://github.com/sacdallago/biotrainer/issues"
repository = "https://github.com/sacdallago/biotrainer"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"

bio-embeddings = "0.2.2"
protobuf = "3.20.0"  # Latest version (4.21.1) conflicts with tensorboard writer
pyyaml = "6.0"
tensorboard = "2.9.0"

[tool.poetry.dev-dependencies]
pytest = "7.1.2"

[tool.poetry.extras]
# TODO: Add options depending on bio-embeddings (prottrans, esm ..)

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
